
#ifndef DELETE_H
#define DELETE_H

#include <string.h>
#include <iostream>

/*
Thump rules. 
Rule of Zero: This rule states that unless a class deals with ownership of resources, it should have no custom destructors, copy and move constructors, and, respectively, copy and move assignment operators
Rule of Five: For class special member functions is that if you explicitly define any copy constructor, move constructor, copy assignment operator, move assignment operator, or destructor, then you must either explicitly define or default all of them
*/

/**
 * **** Defaulted and deleted functions ****
 * Note:
 *1.  If a user-defined constructor exists, -> default constructor is not generated by default
 *2.  If a user-defined virtual destructor exists, -> the default destructor is not generated
 *3.  If move constructor or move assignment operator exists,
 * -> then the copy constructor and copy assignment operator are not generated by default.
 *4.  user-defined copy constructor, move constructor, copy assignment operator, move assignment operator, or destructor exists, 
 *  -> then the move constructor and move assignment operator are not generated by default.
 * If a user-defined copy constructor or destructor exists, -> copy assignment operator is generated by default
 * If a user-defined copy assignment operator or destructor exists -> copy constructor is generated by default
 *
 * In above cases when default implementation is not provided, if required, use =default in the definition of a function, it will provide the default implementation
 * 
 * class foo
 * {
 * public:
 *      foo() = default;
 *      inline foo& operator=(foo const &);
 * };
 * Functions can be declared =default outside the body of a class if and only if they are inlined
 * inline foo& foo::operator=(foo const &) = default;
 */

class Data
{

    public:
        Data()
        : age{0}
        , name {nullptr}
        {

        }

        Data(const char * name, int age)
        : age{age}
        {
            if(name){
                this->name = new char[strlen(name) + 1];
                strcpy(this->name, name);
            }
        }

        Data(const Data & data) 
        {
            age = data.age;

            if(data.name){
                name = new char[strlen(data.name) + 1]; // deep copy
                strcpy(name, data.name);
            }
            else{
                name = nullptr;
            }
        }

        Data & operator = (const Data& data)
        {
            if(this != &data){

                if(name != nullptr)
                    delete [] name;

                age = data.age;

                if(data.name){
                    name = new char[strlen(data.name) + 1]; // deep copy
                    strcpy(name, data.name);
                }
                else{
                    name = nullptr;
                }
            }
            return *this;
        }

        // Method to display the string
        void display() const {
            if (name) {
                std::cout << name << ": " << age << std::endl;
            } else {
                std::cout << "Empty string" << std::endl;
            }
        }

        ~Data()
        { 
            delete[] name;
        }

    private: 


    int age;
    char * name;

};


//To implement a class that is not copyable but is movable, 
// declare the copy operations as deleted and explicitly implement the move operations (and provide any additional constructors 
//that are needed):

class data_wrapper
{

    public:
    data_wrapper(Data * d = nullptr)
    : data(d)
    {}
    
    ~data_wrapper()
    {
        if(data != nullptr){
            delete data;
            data = nullptr;
        }
    }

    data_wrapper(const data_wrapper & other)  = delete;
    data_wrapper & operator =(const data_wrapper & other)  = delete;

    data_wrapper(data_wrapper && other)
    : data(std::move(other.data))
    {
        other.data = nullptr;
    }

    data_wrapper & operator=(data_wrapper && other)
    {
        if(data != other.data){

            delete data;
            data = std::move(other.data);
            other.data = nullptr;
        }
        return *this;
    }

    explicit operator bool() const {
        return (data != nullptr);
    }

    void printData(){
        if(data)
            data->display();
        else
            std::cout << "Empty data" << std::endl;
    }


    private:

    Data *data;

};

//To ensure a function is called only with objects of a specific type
template <typename T>
void run(T val) = delete;
void run(long val) {} // can only be called with long integers

#endif